### ISSUE TITLE
src/main.cpp:20:3: error: 'Serial' was not declared in this scope

### ISSUE THREAD

**Issue by aminggoodboy** [Starryccc/DingDing_WiFi#1]
总是报错这个该如何解决啊老哥！
src/main.cpp:20:3: error: 'Serial' was not declared in this scope

**Comment by Starryccc** [comment]
什么板子，platformio.ini 加这两句没有
`build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1`

**Comment by aminggoodboy** [comment]
加了，我都怀疑是我板子不支持。
![Uploading 062615143127_01.jpg…]()

**Comment by aminggoodboy** [comment]
加了，我都怀疑是我板子不支持。
![062615143127_01](https://github.com/Starryccc/DingDing_WiFi/assets/95681550/1d954d9a-582f-4374-a6a5-7cf653097c63)

**Comment by Starryccc** [comment]
ESP32 不用这个，把build_flags这三行删了，然后把第二行改成 `board = nodemcu-32s`

**Comment by aminggoodboy** [comment]
我直接更换了ESP32C3，目前是已经烧录成功了，但是却不会自动跳转到web设置界面，有没有手动设置的地方

**Comment by Starryccc** [comment]
> 我直接更换了ESP32C3，目前是已经烧录成功了，但是却不会自动跳转到web设置界面，有没有手动设置的地方

littlefs文件上传了吧，浏览器进192.168.4.1

**Comment by aminggoodboy** [comment]
能不能用这个方法打包成Bin文件，方便直接使用，目前我测试还是无法进入192.168.4.1，看烧录的过程是有littlefs.co文件的

**Comment by Starryccc** [comment]
<img width="556" alt="image" src="https://github.com/Starryccc/DingDing_WiFi/assets/14125820/e2e6628f-32e4-4cb4-97db-1b3ab21872f0">

我觉得你应该是没有上传，实在不行你直接改代码吧 

<img width="560" alt="image" src="https://github.com/Starryccc/DingDing_WiFi/assets/14125820/ae26b4eb-544b-46cd-99d9-61016a630a61">
